### ISSUE TITLE
Quick Press of Button messes up PIO on DebouncerLowPIO

### ISSUE THREAD

**Issue by brandoningli** [benevpi/DebouncerPIO#1]
# Expected Behavior
Quickly pressing a button won't register a press, but will allow for a subsequent press.

# Actual Behavior
Quickly pressing and releasing a button messes up the state machine somehow and prevents all subsequent presses until the board is reset.

# Steps to Reproduce

1. Start the button object
2. Press and release the physical button very rapidly

# Additional Information
The same behavior isn't observed when using `DebouncerHighPIO`

**Comment by benevpi** [comment]
Thanks for the bug report. I'll give it a test. Can I just confirm that
you're using the latest version of Debouncer PIO (I updated it yesterday)?
You'll need the latest micropython firmware (from
https://www.raspberrypi.org/documentation/pico/getting-started/) in order
for it to run properly as there's a new feature in PIO which this needs.

Thanks,

Ben

**Comment by brandoningli** [comment]
Yes, I'm running the latest version of both your script and the micropython firmware.

**Comment by benevpi** [comment]
Hmm.

I think we're hitting a bug on MicroPython PIO. I think it does something odd sometimes when you have a label at the end of a program - I hit this before with debouncerHigh, but didn't seem to get it on Low. I've added an extra instruction that does nothing at the end. I *think* that will solve it, but I've had trouble reproducing it here, so let me know how you get on.

**Comment by brandoningli** [comment]
That patch seems to have fixed the issue.
